### ISSUE TITLE
build fails when AVX512 is enabled

### ISSUE THREAD

**Issue by RoadRunnr** [VectorCamp/vectorscan#10]
Build fails with:

<<PKGBUILDDIR>>/src/util/arch/x86/simd_utils.h:655:16: warning: implicit declaration of function ‘set512_64’; did you mean ‘set2x64’? [-Wimplicit-function-declaration]
  655 |     m512 idx = set512_64(3ULL, 2ULL, 1ULL, 0ULL, 7ULL, 6ULL, 5ULL, 4ULL);

Seems there is a helper missing. Hyperscan 5.4.0 has it.

Full log with further failure here:
https://launchpadlibrarian.net/519994259/buildlog_ubuntu-focal-amd64.vectorscan_5.4.0-0ubuntu1~focal_BUILDING.txt.gz

**Comment by markos** [comment]
I'm on it and a new 5.4.x hotfix, with other stuff, thanks for the pointer.

**Comment by markos** [comment]
Hi @RoadRunnr could you please try https://github.com/VectorCamp/vectorscan/tree/v5.4.1+vectorscan?

**Comment by markos** [comment]
forgot to bump versions, try v5.4.2+vectorscan instead?

**Comment by RoadRunnr** [comment]
Seems to work, my ppa package now builts successful on amd64 and arm64.
