### ISSUE TITLE
build with mingw-w64?

### ISSUE THREAD

**Issue by liquidaty** [VectorCamp/vectorscan#117]
It would be great if this fork supported compilation with mingw-w64. 

UPDATE: With some minor modifications, we've managed to compile simplegrep.exe on OSX+mingw-w64. This requires a minor change in src/util/alloc.cpp to use `__mingw_aligned_malloc()` instead of `posix_memalign()` and `__mingw_aligned_free()` instead of `free()` in `aligned_free_internal`.

Will you consider incorporating these changes if we create a PR? There are still other issues to resolve (such as getting it to properly use AVX2 instead of only working with SSE), but if if this fork doesn't officially support minGW, this change would at least provide a way to get an unsupported minimal working version with this toolchain, without impacting other builds

**Comment by markos** [comment]
@liquidaty hi, I would suggest you try the original project for OSX/Intel platform. While it should be easy to get vectorscan working on this platform, we don't have the hardware and don't intend to support it. However, if the PR is trivial and non-intrusive -ie it doesn't break things for other platforms and is zero/low-cost on maintainance, we would be open to merge it.

**Comment by liquidaty** [comment]
@markos thank you! I appreciate that you will consider it and will send a PR shortly

**Comment by markos** [comment]
Fixed in https://github.com/VectorCamp/vectorscan/pull/121

**Comment by liquidaty** [comment]
thank you!
