### ISSUE TITLE
vectorscan 5.4.8 error: cannot use 'char' with '__vector bool' on alpine ppc64le

### ISSUE THREAD

**Issue by a16bitsysop** [VectorCamp/vectorscan#126]
when compiling 5.4.8 with clang 14.0.6 on alpine I get the following error:

```
/builds/a16bitsysop/aports/community/vectorscan/src/vectorscan-vectorscan-5.4.8/src/util/supervector/arch/ppc64el/impl.cpp:52:49: error: cannot use 'char' with '__vector bool'
[620](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/839733#L620)really_inline SuperVector<16>::SuperVector(char __bool __vector v)
```
Full log:
https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/839733/raw

If it is patched with:

```
--- a/src/util/supervector/arch/ppc64el/impl.cpp
+++ b/src/util/supervector/arch/ppc64el/impl.cpp
@@ -49,7 +49,7 @@
 
 template<>
 template<>
-really_inline SuperVector<16>::SuperVector(char __bool __vector v)
+really_inline SuperVector<16>::SuperVector(__vector __bool char v)
 {
     u.u8x16[0] = (uint8x16_t) v;
 };
```

It compiles but there are alot of test failures:
https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/839792

**Comment by markos** [comment]
Hi @a16bitsysop indeed I confirm here that compiling with clang 14 produces numerous tests failing -with the fix. I will have to investigate and will roll out a new release with a fix soon.

**Comment by a16bitsysop** [comment]
thanks

**Comment by markos** [comment]
Fixed in https://github.com/VectorCamp/vectorscan/pull/129
