### ISSUE TITLE
Vectorscan 5.4.9 reports its version as 5.4.8

### ISSUE THREAD

**Issue by mistydemeo** [VectorCamp/vectorscan#138]
It looks like the version constants in `CMakeLists.txt` weren't updated for release 5.4.9, so `hs_version()` returns `5.4.8`. https://github.com/VectorCamp/vectorscan/blob/master/CMakeLists.txt#L5-L7

**Comment by markos** [comment]
sorry about that, please ignore it, it was a wrong tag, 5.4.9 has not been released yet, when it is it will be in the releases page as usual. Accidental tag has been removed.
