### ISSUE TITLE
vectorscan version incorrect in hs.h

### ISSUE THREAD

**Issue by a16bitsysop** [VectorCamp/vectorscan#140]
rspamd has implemented a version check for hyperscan files in commit:
https://github.com/rspamd/rspamd/commit/5604cdc3e0b2f2e94ce99a83655b7939cde01ebe

for the current version of vectorscan this always fails with:
`invalid version: 84150272 (84148224 expected)`

I can’t see any code for rspamd saving the version, these numbers are 2048 different which is 1<<11

I can see is hs.h the patch number is `0` not `8`

**Comment by a16bitsysop** [comment]
the header has now been patched in alpine, which fixes the test for rspamd.

**Comment by markos** [comment]
Hi, a -long overdue- vectorscan version will be released in the next few days, and this fix will be included. thanks for your contributions!

**Comment by markos** [comment]
This has been fixed in #135 . A new release is planned soon.
