### ISSUE TITLE
merge latest hyperscan commits

### ISSUE THREAD

**Issue by sambercovici** [VectorCamp/vectorscan#168]
It looks like there are additional commits on the hyperscan git repository that ae not covered by this fork.
Does it make sense to "rebase"?

**Comment by markos** [comment]
A new release (5.4.10) is planned soon, some of those commits will be cherry-picked.

**Comment by markos** [comment]
All relevant fixes were backported from Hyperscan to develop branch (#169 ). When internal CI completes successfully, we will proceed to 5.4.10 release.
