### ISSUE TITLE
Using Vectorscan in Envoyproxy

### ISSUE THREAD

**Issue by sambercovici** [VectorCamp/vectorscan#171]
Hi @markos

I am proposing, for the Envoyproxy project, to to add support for additional CPUs over the x64 for extensions depending on Hyperscan using Vectorscan.

See the comment: https://github.com/envoyproxy/envoy/issues/29276#issuecomment-1709310387
"I have concerns about the supply chain security of this component. It appears that this project lacks CI assurance, proper unit testing and Fuzzing testing."

Can you please address this in the issue thread?

**Comment by markos** [comment]
Though it's nice to have, this is not actually a bug in Vectorscan, it's a wishlist task in another project, which we cannot contro, so I'm going to close this, I hope you understand.
