### ISSUE TITLE
5.4.10 build failure

### ISSUE THREAD

**Issue by chenrui333** [VectorCamp/vectorscan#172]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  /tmp/vectorscan-20230907-31078-ev28ln/vectorscan-vectorscan-5.4.10/src/util/arch/arm/cpuid_inline.h:33:10: fatal error: 'sys/auxv.h' file not found
  #include <sys/auxv.h>
           ^~~~~~~~~~~~
  1 error generated.
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/6113993720/job/16601392063?pr=141717
relates to Homebrew/homebrew-core#141717

**Comment by markos** [comment]
Sigh, fat binary on arm will only work on Linux, this is an oversight on my side, I will fix and prepare a new release asap.

**Comment by markos** [comment]
Could you please check 5.4.10.1? It should be fixed now.

**Comment by chenrui333** [comment]
the version works for me except the version number (which is a minor issue), thanks for the fix.

**Comment by chenrui333** [comment]
@markos also let me know if you can make a new release. Thanks!

**Comment by markos** [comment]
5.4.11 is planned soon, but not right away.

**Comment by chenrui333** [comment]
awesome!
