### ISSUE TITLE
OSSF Scorecard result is low

### ISSUE THREAD

**Issue by sambercovici** [VectorCamp/vectorscan#182]
Hi,

See: https://github.com/envoyproxy/envoy/pull/29881#discussion_r1345052941
Please let me know if this can be improved.
Also let me know if I can assist.

-Sam.

**Comment by markos** [comment]
I have replied to the issues there, but we will not do anything extra to improve the score. It's artificially low, they never even bothered to check that it's already packaged in Debian and there is a debian branch here. I'm sorry but we already beat original Hyperscan in most of the things requested. Closing this bug.
