### ISSUE TITLE
Install doesn't include hs_version.h

### ISSUE THREAD

**Issue by gliwka** [VectorCamp/vectorscan#198]
After compiling and installing vectorscan locally, the hs_version.h is missing in the installed header files:

```
/work/hyperscan-java-native/cppbuild/include/hs/hs.h:42:10: fatal error: hs_version.h: No such file or directory
   42 | #include "hs_version.h"
```

```
[root@e2de98379481 include]# find .
.
./hs
./hs/hs_common.h
./hs/hs_runtime.h
./hs/hs.h
./hs/hs_compile.h
```

It seems to me that this is related to the change making sure that the version numbers don't get out of sync:
https://github.com/VectorCamp/vectorscan/commit/16604f9539929b5d19dc81d529c36770fd8eebfd

Now hs_version.h is suddenly part of the required development headers, which was not the case before.

**Comment by markos** [comment]
Sigh, indeed, we went through all this trouble to fix the build for all the compilers/configurations but we forgot to check the installation :)
