### ISSUE TITLE
use SIMDe to add plain amd64 (SSE2) to the FAT_RUNTIME

### ISSUE THREAD

**Issue by mr-c** [VectorCamp/vectorscan#204]
This doesn't have to be the default, but it would aid Debian, Fedora, and others who still have to support plain x86-64 systems that only have SSE2

(I tried, but it was a bit beyond me).

Thanks!

**Comment by markos** [comment]
that makes sense, it would also avoid the sse4.2 pseudo-package dependency in Debian.
