### ISSUE TITLE
Unable to compile by Visual Studio 2017 

### ISSUE THREAD

**Issue by vmurashev** [VectorCamp/vectorscan#23]
Is windows platform supported at all by this fork of intel/hyperscan ?
When I tried to build it by Visual Studio 2017 for x86_64,
a lot of errors generated:
```
c:\devl\hs2\1\src\util/arch/common/bitutils.h(42): error C3861: '__builtin_clz': identifier not found [C:\devl\hs2\1\build\hs_compile.vcxproj]
c:\devl\hs2\1\src\util/arch/common/bitutils.h(47): error C3861: '__builtin_clzll': identifier not found [C:\devl\hs2\1\build\hs_compile.vcxproj]
c:\devl\hs2\1\src\util/arch/common/bitutils.h(53): error C3861: '__builtin_ctz': identifier not found [C:\devl\hs2\1\build\hs_compile.vcxproj]
c:\devl\hs2\1\src\util/arch/common/bitutils.h(58): error C3861: '__builtin_ctzll': identifier not found [C:\devl\hs2\1\build\hs_compile.vcxproj]
c:\devl\hs2\1\src\util/arch/common/bitutils.h(407): error C3861: '__builtin_popcountl': identifier not found [C:\devl\hs2\1\build\hs_compile.vcxproj]
c:\devl\hs2\1\src\util/arch/common/bitutils.h(413): error C3861: '__builtin_clzl': identifier not found [C:\devl\hs2\1\build\hs_compile.vcxproj]
c:\devl\hs2\1\src\util/arch/x86/bitutils.h(146): error C3861: 'ctz64': identifier not found [C:\devl\hs2\1\build\hs_compile.vcxproj]
```

More then that if to workaround above errors with a couple fixes in files
```
src/util/arch/common/bitutils.h
src/util/arch/x86/bitutils.h
```
than is possible to proceed with compilation, but later build fails anyway with the following errors:
```
C:\devl\hs2\1\src\util/arch/x86/simd_utils.h(56): error C2440: 'type cast': cannot convert from '__m128i' to 'm128' [C:\devl\hs2\1\build\hs_exec.vcxproj]
C:\devl\hs2\1\src\util/arch/x86/simd_utils.h(61): error C2440: 'type cast': cannot convert from '__m128i' to 'm128' [C:\devl\hs2\1\build\hs_exec.vcxproj]
C:\devl\hs2\1\src\fdr\teddy.c(1073): error C2143: syntax error: missing ')' before '(' [C:\devl\hs2\1\build\hs_exec.vcxproj]
...
```
Please advice

**Comment by markos** [comment]
@vmurashev Windows support is currently investigated for this fork. We are not certain we will continue to support Windows. Please use the original project instead.

**Comment by vmurashev** [comment]
I am looking for a fork where from same sources it is possible to build hyperscan for:
- windows x86,x64
- Linux x64
- MacOS x64, arm64

**Comment by markos** [comment]
@vmurashev I would use the original hyperscan repo for that. As it is, we're probably going to keep support for MacOS, but Windows support is going to be removed entirely, mostly to simplify the codebase and avoid all those #ifdefs. Our focus is on portability between multiple architectures on Linux/Unix-type OSes, in the near future we will also add MacOS/ARM support.
