### ISSUE TITLE
Combo pattern fails when operands set singlematch flag and/or max_offset

### ISSUE THREAD

**Issue by ghost** [VectorCamp/vectorscan#240]
The following test cases show unintuitive behavior when running on "buffer": b"0123"

`"patterns": [ "/(1 & 2)/C", "/01/H", "/23/H", ], "result": [1, 2]`
`"patterns": [ "/(1 & 2)/HC", "/01/H{max_offset=2}", "/23/H", ], "result":[1, 2]`
`"patterns": [ "/(1 & 2)/C", "/01/H{max_offset=2}", "/23/H",  ], "result": [1, 2]`

Expected behavior:
`"patterns": [ "/(1 & 2)/HC", "/01/H", "/23/H", ], "result": [1, 2, 0]`

**Comment by ghost** [comment]
Proposed fix:
```
diff --git a/src/rose/stream.c b/src/rose/stream.c
index 26268dd..33e29db 100644
--- a/src/rose/stream.c
+++ b/src/rose/stream.c
@@ -534,16 +534,20 @@ int can_never_match(const struct RoseEngine *t, char *state,
         return 0;
     }

     if (mmbit_any(getActiveLeafArray(t, state), t->activeArrayCount)) {
         DEBUG_PRINTF("active leaf\n");
         return 0;
     }

+    if (t->ckeyCount) {
+        return 0;
+    }
+
     return 1;
 }

 void roseStreamExec(const struct RoseEngine *t, struct hs_scratch *scratch) {
     DEBUG_PRINTF("OH HAI [%llu, %llu)\n", scratch->core_info.buf_offset,
                  scratch->core_info.buf_offset + (u64a)scratch->core_info.len);
     assert(t);
     assert(scratch->core_info.hbuf);
```

**Comment by gtsoul-tech** [comment]
We've tested the patterns you provided using the hs_scan function in a unit test, and they seem to work as expected. However, the behavior might differ based on the specific function call you're using in your code.

Could you please provide the exact function call you're using to test these patterns?

**Comment by ghost** [comment]
I ran these tests with hs_scan_stream as well as hs_scan. Feel free to close it if non-reproducible... These test were run on the hyperscan repository

**Comment by markos** [comment]
This isn't actually a bug in vectorscan, closing.
