### ISSUE TITLE
Wrong web site URL in this GitHub repo

### ISSUE THREAD

**Issue by ryandesign** [VectorCamp/vectorscan#241]
At the top right of this GitHub repo's main page it lists the project's web site as https://www.vectorcamp.gr/vectorscan/. archive.org shows that this used to be the project's web site however now it just redirects to https://www.vectorcamp.gr. The page specific to the vectorscan project now appears to be https://www.vectorcamp.gr/project/vectorscan/ so please update the URL in this GitHub repo and also fix the www.vectorcamp.gr web server so that it redirects the old URL to the new one. Thank you.

**Comment by markos** [comment]
Thank you, that was a good catch! It was missed during a recent reorg in the website, we fixed the URL on github, will soon fix the redirect as well.
