### ISSUE TITLE
unit-internal and unit-hyperscan segfault on FreeBSD/ppc64le

### ISSUE THREAD

**Issue by markos** [VectorCamp/vectorscan#243]
For example:

https://buildbot-ci.vectorcamp.gr/#/builders/206/builds/10
https://buildbot-ci.vectorcamp.gr/#/builders/187/builds/10

**Comment by isildur-g** [comment]
the rpath hack is sort of a red herring for this bug -  there is an incompatibility between more recent libgcc and the libs in the base distribution and the rpath hack was needed to get the binaries to link properly. 
In the course of this we also ran into some segfaults on powerpc, which are not related to the rpath issue, but do seem to be potentially compiler-dependent. They are encountered in freebsd/ppc with clang16, clang17, and gcc13, depending on various build parameters. with gcc12 it seems to work in all cases. 
the problem could be an alignment issue or a size plus alignment issue. One of the more promising leads in debugging is recounted here:
uname -a
FreeBSD devel-freebsd14-ppc64le-01 14.0-RELEASE FreeBSD 14.0-RELEASE #0 releng/14.0-n265380-f9716eee8ab4: Fri Nov 10 05:56:19 UTC 2023     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/powerpc.powerpc64le/sys/GENERIC64LE powerpc
build configured with cmake -DBUILD_STATIC_LIBS=True -DBUILD_SHARED_LIBS=True -DCMAKE_BUILD_TYPE=Release -DFAT_RUNTIME=False -DCMAKE_C_COMPILER=clang16 -DCMAKE_CXX_COMPILER=clang++16 ../

in unit-hyperscan, in regression test UE_2452, we end up doing a memset where the size is an obviously wrong and very large value fffffffffffffec0. This size is taken from the size() call on a std::vector<u8> which is allocated relatively nearby to where the problem occurs, and on allocation its size if correct. The vector's metadata at least is getting corrupted by something else in the way. At present resources are not available to devote to debugging further but a stack trace is copied here to save for later: 
#0  0x0000000810c39920 in memset (dst0=0x811843f40, c0=0, length=18446744073709551296)
    at /usr/src/lib/libc/string/memset.c:120
#1  0x0000000010376450 in ue2::small_color_map<ue2::ue2_graph<ue2::NGHolder, ue2::NFAGraphVertexProps, ue2::NFAGraphEdgeProps>::prop_map<unsigned long const&, ue2::NFAGraphVertexProps> >::fill (this=<optimized out>, 
    color=ue2::small_color::white)
    at /home/groik/vsnb/vectorscan-build-on-netbsd/src/util/graph_small_color_map.h:121
#2  ue2::searchForward<boost::reverse_graph<ue2::NGHolder, ue2::NGHolder&>, ue2::small_color_map<ue2::ue2_graph<ue2::NGHolder, ue2::NFAGraphVertexProps, ue2::NFAGraphEdgeProps>::prop_map<unsigned long const&, ue2::NFAGraphVertexProps> > > (reach=..., colours=..., s=..., g=..., w=...)
    at /home/groik/vsnb/vectorscan-build-on-netbsd/src/nfagraph/ng_cyclic_redundancy.cpp:134
#3  ue2::removeCyclicPathRedundancy<boost::reverse_graph<ue2::NGHolder, ue2::NGHolder&> > (v=..., raw=..., g=...)
    at /home/groik/vsnb/vectorscan-build-on-netbsd/src/nfagraph/ng_cyclic_redundancy.cpp:208
#4  ue2::cyclicPathRedundancyPass<boost::reverse_graph<ue2::NGHolder, ue2::NGHolder&> > (raw=..., g=...)
    at /home/groik/vsnb/vectorscan-build-on-netbsd/src/nfagraph/ng_cyclic_redundancy.cpp:235
#5  ue2::removeCyclicPathRedundancy (g=...)
    at /home/groik/vsnb/vectorscan-build-on-netbsd/src/nfagraph/ng_cyclic_redundancy.cpp:255
#6  0x000000001035820c in ue2::reduceGraph (g=..., som=ue2::SOM_NONE, utf8=<optimized out>, cc=...)
    at /home/groik/vsnb/vectorscan-build-on-netbsd/src/nfagraph/ng.cpp:175
#7  0x0000000010358ee0 in ue2::addComponent (ng=..., g=..., expr=..., som=(unknown: 0xbfffd7b0), comp_id=0)
    at /home/groik/vsnb/vectorscan-build-on-netbsd/src/nfagraph/ng.cpp:217
#8  ue2::processComponents (ng=..., expr=..., g_comp=std::deque with 1 element = {...}, som=ue2::SOM_NONE)
    at /home/groik/vsnb/vectorscan-build-on-netbsd/src/nfagraph/ng.cpp:305
#9  0x00000000103588c4 in ue2::NG::addGraph (this=0xfffffbfffd960, expr=..., g_ptr=...)
    at /home/groik/vsnb/vectorscan-build-on-netbsd/src/nfagraph/ng.cpp:482
#10 0x0000000010354514 in ue2::addExpression (ng=..., index=0, 
    expression=0x8110d5900 "/ab.b[bca]{2,}ca((?:c|(abc(?sxmi-xm)){10,14}|c|b|[abcb])){4,23}acbcbb*ba((?:(a|.{4,}|.|[acba])){3,16}a)+", flags=229, ext=0x8110f7e00, id=<optimized out>)
    at /home/groik/vsnb/vectorscan-build-on-netbsd/src/compiler/compiler.cpp:385
#11 0x00000000103511b4 in ue2::hs_compile_multi_int (expressions=0x811008b98, flags=0x811008b90, ids=0x811008a50, 
    ext=<optimized out>, elements=1, mode=<optimized out>, platform=<optimized out>, db=0xfffffbfffe128, 
    comp_error=<optimized out>, g=...) at /home/groik/vsnb/vectorscan-build-on-netbsd/src/hs.cpp:244
#12 0x00000000103525ec in hs_compile_ext_multi (expressions=<optimized out>, flags=<optimized out>, 
    ids=<optimized out>, ext=<optimized out>, elements=<optimized out>, mode=<optimized out>, 
    platform=<optimized out>, db=<optimized out>, error=<optimized out>)
    at /home/groik/vsnb/vectorscan-build-on-netbsd/src/hs.cpp:456
#13 0x0000000010268088 in buildDB (patterns=..., mode=<optimized out>, plat=<optimized out>)
    at /home/groik/vsnb/vectorscan-build-on-netbsd/unit/hyperscan/test_util.cpp:78
#14 0x00000000101a7c0c in (anonymous namespace)::regression_UE_2452_Test::TestBody (this=<optimized out>)
    at /home/groik/vsnb/vectorscan-build-on-netbsd/unit/hyperscan/behaviour.cpp:1368
#15 0x0000000010114dec in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (
    method=<optimized out>, location=0x1001a8be "the test body", object=<optimized out>)
    at /home/groik/vsnb/vectorscan-build-on-netbsd/unit/gtest/gtest-all.cc:3562
#16 testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0x81101e3a0, 
    method=<optimized out>, location=0x1001a8be "the test body")
    at /home/groik/vsnb/vectorscan-build-on-netbsd/unit/gtest/gtest-all.cc:3598
#17 0x00000000100fcc44 in testing::Test::Run (this=0x81101e3a0)
