### ISSUE TITLE
Fix all errors/warnings found by Clang-tidy

### ISSUE THREAD

**Issue by gtsoul-tech** [VectorCamp/vectorscan#253]
debug-linux-aarch64-clang-17-clang-tidy
https://buildbot-ci.vectorcamp.gr/#/builders/266/builds/95

debug-linux-ppc64le-clang-17-clang-tidy
https://buildbot-ci.vectorcamp.gr/#/builders/271/builds/98

debug-linux-x86-clang-17-clang-tidy
https://buildbot-ci.vectorcamp.gr/#/builders/267/builds/81
headers
 6 clang-analyzer-core.StackAddressEscape #296
4 clang-analyzer-core.uninitialized.UndefReturn #295
1 clang-analyzer-cplusplus.Move #295
TODO: 11 clang-analyzer-cplusplus.NewDelete #295  remaining 10 in boost library to be ingored
67 clang-analyzer-deadcode.DeadStores #295 #296 #298 (remaining 55 warnings in build/src/parser and fdr,teddy that will be redactored) #299
 3 clang-analyzer-optin.cplusplus.VirtualCall #296
13 clang-analyzer-optin.performance.Padding #293 #298
419 clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling to be ignored #299
 2 clang-analyzer-valist.Uninitialized  gtest #299

**Comment by markos** [comment]
All remaining clang-tidy warnings fixed in #300
