### ISSUE TITLE
Test for Alignr128c for Intel currently failing.

### ISSUE THREAD

**Issue by geowor01** [VectorCamp/vectorscan#44]
https://github.com/VectorCamp/vectorscan/commit/a1eaf89f3aba07f0c8bfa1dda7774d61d50d7f2e#r52764543

**Comment by geowor01** [comment]
SuperVector's alignr isn't actually being used at the moment though.

**Comment by markos** [comment]
Fixed in https://github.com/VectorCamp/vectorscan/commit/8d666dd464b9cba5eeaa8dac363664cf55f85f0c
