### ISSUE TITLE
shuftiExec() and truffleExec() are vectorscan code hot spot for Snort3 on arm

### ISSUE THREAD

**Issue by liangxwa01** [VectorCamp/vectorscan#59]
Vectorscan version:  **v5.4.2+vectorscan**
Hyperscan version: **v5.4.2**

When Snort3 inspects one .pcap packets file with same configuration, the vectorscan module profiling result on **arm** (around 2900 milliseconds) is almost twice as much as hyperscan profiling result on **x86** (around 1600 milliseconds). From the perf analysis result, shuftiExec() and truffleExec() are vectorscan code hot spot on arm, but this is not the case for x86 hyperscan. Any idea or suggestion for vectorscan here? Thanks.

Snort 3 with Arm vectorscan perf result:

<img width="752" alt="arm" src="https://user-images.githubusercontent.com/87638870/128719322-c5b4c89e-993b-4a78-bd62-c0644e4d64c1.PNG">

Snort 3 with x86 hyperscan perf result:

<img width="748" alt="x86" src="https://user-images.githubusercontent.com/87638870/128719394-5a3beca3-8316-493b-8354-d17d840ec117.PNG">

**Comment by markos** [comment]
@liangxwa01, I see you are trying v5.4.2+vectorscan revision, could you please try current develop branch? Or could you provide a way to reproduce this with snort3?

**Comment by liangxwa01** [comment]
Thanks @markos . Let me switch to the develop branch and try it firstly.

**Comment by markos** [comment]
@liangxwa01 sigh, yes, you need to add -DOPTIMISE=on -DCMAKE_BUILD_TYPE=Release. OPTIMISE will be removed in a next commit and optimized paths will be enabled for Release mode automatically.

**Comment by liangxwa01** [comment]
@markos , with -DOPTIMISE=on -DCMAKE_BUILD_TYPE=Release, libhs* performance from develop branch is similar as original v5.4.2+vectorscan. shuftiExecReal() and truffleExecReal() are still code hot spots on arm. Any further thoughts?  Setting up Snort3 is a bit complicated. Do you have an arm server running ubuntu 20.04?

![arm_hs_dev](https://user-images.githubusercontent.com/87638870/129166152-6afe6561-56d8-4816-83e2-cea13bac244f.PNG)

**Comment by liangxwa01** [comment]
@markos Sure.

Annotate shuftiExecReal<(unsigned short)16> : 
![arm_hs_dev1](https://user-images.githubusercontent.com/87638870/129168444-38b00239-505e-4962-8a6a-125355176267.PNG)

Annotate truffleExecReal<(unsigned short)16> :
![arm_hs_dev1](https://user-images.githubusercontent.com/87638870/129168678-907dff93-b091-419e-9f41-d42eb567b77b.PNG)

Do these help?

**Comment by markos** [comment]
@liangxwa01 yes, a lot, I will investigate immediately. Thanks

**Comment by markos** [comment]
@liangxwa01 ok is the main for loop in both Shufti/Truffle, it appears memory prefetching is not having the same effect on ARM, causing a stall waiting for the next data to be loaded to a vector, probably the stride needs to be different, I'll experiment a bit more with this.

**Comment by liangxwa01** [comment]
@markos thanks for the update. Feel free to let me know if I can help try something.

**Comment by liangxwa01** [comment]
@markos any progress for this issue? Thanks.

**Comment by markos** [comment]
@liangxwa01 Is it ok to close this issue for now?

**Comment by liangxwa01** [comment]
@markos yes, you can close it. Thanks.
