### ISSUE TITLE
Test failure on x86_64 with version 5.4.6 on alpine linux

### ISSUE THREAD

**Issue by a16bitsysop** [VectorCamp/vectorscan#88]
I initially tried the options from the Debian branch, which passed on the alpine ci but failed on the builder.

The builder does not have avx2 so I changed `-DBUILD_AVX2=on` To off, but the same test failed 

```
[ RUN      ] HyperscanArgChecks.ChangeStreamContext
Illegal instruction (core dumped)
```

so I changed back to -march=core2, which says tuning for sse4.2 but fails the same

https://gitlab.alpinelinux.org/alpine/aports/-/issues/13470

**Comment by markos** [comment]
Hi, if you're building with FAT_RUNTIME=on it should not matter if the builder has no AVX2/AVX512 just to compile the library. However, there is no point building a fat runtime only with SSE4.2. The library should run on any system and autodetect the right engine to use. However to run the tests with FAT_RUNTIME you should have at least AVX2 (it is auto-enabled when FAT_RUNTIME is set to on. In any case, if you really only want just SSE4.2 then you should also set FAT_RUNTIME=off. Or upgrade the builder if that's an option.

So, I would see 3 options: a) disable the tests while building a fat runtime with all engines enabled, b) Compile with SSE4.2 only and FAT_RUNTIME=off and run the tests, c) Upgrade the builder hardware.

**Comment by a16bitsysop** [comment]
Okay, will build a fat runtime and disable the failing test

**Comment by a16bitsysop** [comment]
It worked with disabling the one test with a fat runtime and same options as Debian branch, thanks.
