### ISSUE TITLE
Release tarball has double directory 

### ISSUE THREAD

**Issue by a16bitsysop** [VectorCamp/vectorscan#9]
When unpacking the source tarball it creates vectorscan-vectorscan-v5.4.0

**Comment by markos** [comment]
thanks for the pointer, new hotfix release imminent.

**Comment by markos** [comment]
Hi @a16bitsysop could you please try https://github.com/VectorCamp/vectorscan/tree/v5.4.1+vectorscan?

**Comment by a16bitsysop** [comment]
@markos Yes it compiles for alpine, but the libs are called `libhs_runtime.so.5.4.0` and `libhs.so.5.4.0`

It looks like they haven't been bumped?

**Comment by markos** [comment]
sigh, yes, please try v5.4.2+vectorscan instead, sorry about that.

**Comment by a16bitsysop** [comment]
Yes thats better, thanks
