### ISSUE TITLE
msvc toolchain support?

### ISSUE THREAD

**Issue by windowsair** [VectorCamp/vectorscan#96]
The cmake function `CHECK_C_SOURCE_COMPILES` has poor support for msvc, but it seems to be rarely documented anywhere.

The current status is that we will fail on the `arch.cmake` check. I'm not sure if I need to change more than that.

**Comment by markos** [comment]
I am sorry, Windows/MSVC support has been removed as unsupported. I would suggest you try the original Hyperscan project.

**Comment by windowsair** [comment]
Oh, that's a shame, I would have liked to cross more platforms anyway.
