### ISSUE TITLE
[question] install vectorscan package

### ISSUE THREAD

**Issue by yangzhang21** [VectorCamp/vectorscan#97]
@markos do we support install package through apt-get or we have to build the package on local?
for hyperscan we run `apt-get install -y libhyperscan5` command. do we have something similar for vectorscan? 
thanks.

**Comment by markos** [comment]
@yangzhang21 Hi, it's already in Debian/Ubuntu: https://tracker.debian.org/pkg/vectorscan :)

**Comment by yangzhang21** [comment]
> @yangzhang21 Hi, it's already in Debian/Ubuntu: https://tracker.debian.org/pkg/vectorscan :)

excellent. thanks! @markos

**Comment by yangzhang21** [comment]
@markos , to follow up, if i run `apt-get install -y libvectorscan5` on a ubuntu machine, i get this error ` Unable to locate package libvectorscan5`, any suggestion?

**Comment by markos** [comment]
it should be in the next release: https://launchpad.net/ubuntu/+source/vectorscan

**Comment by yangzhang21** [comment]
> it should be in the next release: https://launchpad.net/ubuntu/+source/vectorscan

any timeline estimate? :)

**Comment by markos** [comment]
you'd have to ask Canonical about that :)

**Comment by istiak101** [comment]
@yangzhang21 available in Ubuntu 22.04 and later in universe repository.

**Comment by yangzhang21** [comment]
> @yangzhang21 available in Ubuntu 22.04 and later in universe repository.

thanks!
